

import { Accordion } from '@material-tailwind/react';
import '../styles/globals.css';
import Header from './Header';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        
<title> Creo's training</title>


      </head>
      <body className="homepage-bg">
        < Header />
      
        {children}
        </body>
    </html>
  )
}
